### ISSUE TITLE
First time running the main script causes error

### ISSUE THREAD

**Issue by pedrohenriquebr** [pedrohenriquebr/Pegasus#2]
Running the first time with 
```bash
$ python main.py --filename extrato_template.csv
```

causes the output:

```bash
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    pegasus.append_dataframe(args.filename)
  File "/mnt/c/Users/pedro/Documents/Dev/Pegasus/pegasus.py", line 76, in append_dataframe
    self.base_df = pd.concat([self.base_df, self.tmp])
AttributeError: 'Pegasus' object has no attribute 'base_df'
```

**Comment by pedrohenriquebr** [comment]
It needs to declare the base_df before `append_dataframe` function

**Comment by pedrohenriquebr** [comment]
I will fix using the `load_dataframe` calling
